# Generated by Django 4.2 on 2023-05-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oficina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Ciudadano", "Ciudadano"),
                            ("Empleado", "Empleado"),
                            ("Administrador", "Administrador"),
                        ],
                        max_length=45,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("mensaje", models.CharField(max_length=2000)),
                ("correo", models.EmailField(max_length=45)),
                ("barrio", models.CharField(max_length=45)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Solicitada", "Solicitada"),
                            ("Atendida", "Atendida"),
                        ],
                        max_length=45,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Peticion", "Peticion"),
                            ("Queja", "Queja"),
                            ("Reclamo", "Reclamo"),
                        ],
                        max_length=45,
                    ),
                ),
                ("fechaRegistro", models.DateTimeField(auto_now_add=True)),
                (
                    "oficina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitudes.oficina",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuestas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.CharField(max_length=2000)),
                ("fechaRegistro", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificacion", models.CharField(max_length=45)),
                ("nombre", models.CharField(max_length=45)),
                ("apellido", models.CharField(max_length=45)),
                ("correo", models.EmailField(max_length=45)),
                (
                    "oficina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitudes.oficina",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitudes.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitudes.respuestas",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
        ),
    ]
